### ISSUE TITLE
Accept callback with hashed filename?

### ISSUE THREAD

**Issue by Rich-Harris** [phamann/rollup-plugin-hash#14]
I have a situation where I have an array of sequential builds in a single config — one for the client, one for the service worker, one for the server — and each config depends on the output of the previous one (service worker needs the hashed bundle filename for the cache manifest, server needs both in order to rewrite templates correctly).

At the moment it's quite finicky to put all those pieces together. What do you think about accepting a callback that is called with the hashed filename, so it can be stored locally and used in subsequent configs?

**Comment by phamann** [comment]
Funnily enough, I came across this exact need in a project of my own today. I'll have a got at fixing this.

**Comment by frederikhors** [comment]
@Rich-Harris something like this in rollup native?
