### ISSUE TITLE
can i only get 8 bytes ？

### ISSUE THREAD

**Issue by zwlcoding** [phamann/rollup-plugin-hash#15]
like webpack 

```javascript
hash({
    dest: 'dist/common.[hash:8].js'
})
```

**Comment by phamann** [comment]
Hi @zwlcoding thanks for you're issue. This has now been implemented in #16 and now been released in [`v1.3.0`](https://github.com/phamann/rollup-plugin-hash/releases/tag/v1.3.0) 🎉
