### ISSUE TITLE
Unreachable code and possibly wrong order.

### ISSUE THREAD

**Issue by BobbyBabes** [phamann/rollup-plugin-hash#21]
This function in `src/index.js` :
[https://github.com/phamann/rollup-plugin-hash/blob/master/src/index.js#L30-L32](https://github.com/phamann/rollup-plugin-hash/blob/master/src/index.js#L30-L32)
```JavaScript
function generateManifest(input, output) {
	return JSON.stringify({[input]: output});
}
```

ends up in
`node_modules/rollup-plugin-hash/dist/rollup-plugin-hash.js`
`node_modules/rollup-plugin-hash/dist/rollup-plugin-hash.es.js`

as :
```JavaScript
function generateManifest(input, output) {
	return JSON.stringify(( obj = {}, obj[input] = output, obj ));
	var obj;
}
```
The `var obj` statement looks like unreachable code to me, and should have come before the `return` statement, I think.

**Comment by phamann** [comment]
:wave: I @BobbyBabes, thank you for submitting the issue. 

The output you're viewing in `node_modules/rollup-plugin-hash/dist/rollup-plugin-hash.js` is the compiled output from the Rollup build process defined [here](https://github.com/phamann/rollup-plugin-hash/blob/master/rollup.config.js), which in turn uses the JavaScript compiler [Bublé](https://buble.surge.sh/) and therefore not an issue of the source code in this project but just a matter of style for the Bublé compiler. 

This is still valid JavaScript and doesn't throw errors at runtime, as even though the variable declaration is after the `return` statement, it will get hoisted at execution time. You can read more about variable hoisting in JavaScript on MDN: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

As this isn't an issue for this project I'm going to close.

**Comment by BobbyBabes** [comment]
I realise that it's not an issue with the source code of this repo. That's why I wrote : `ends up in` `as`.
I just pointed it out. Hoisting of variable declarations is something that should be removed from JavaScript.
But if you don't care how (ugly) your code comes out of a build tool. It's of course OK. ;) Peace!
