### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by mwerezi** [phamann/rollup-plugin-hash#3]
How would one use this plugin on multiple files?

thanks

**Comment by phamann** [comment]
Hi @mwerezi thanks for your question.

Rollup only supports a single entry point (file) for a bundle, and therefore normally only produces a single bundle output. However you can use the [targets](https://github.com/rollup/rollup/wiki/Command-Line-Interface#targets) option to generate different module formats, such as UMD, CommonJS etc.

Just to clarify, are you interested in hashing each target output, or something else?

**Comment by mwerezi** [comment]
Hi @phamann,

I'm using the rollup-plugin-scss, which generates a separate .css file, so it would be for that use

thanks

**Comment by mwerezi** [comment]
In the end, i just used rollup-plugin-sass where you can inject the css  in the js.

**Comment by dtruffaut** [comment]
Rollup nowadays support multiple entries. Is it possible to add a variable such as [filename], so I can ask for my multiple outputs to follow this form: [filename].[hash].js ?
