### ISSUE TITLE
Automatic dest detection

### ISSUE THREAD

**Issue by zdyn** [phamann/rollup-plugin-hash#4]
For my use case, I call rollup from the CLI and pass the dest as an argument. From my understanding, the current best (only?) practice is to set plugin options in a rollup config file. However, I cannot set the dest as a hash plugin option in the config file because it is not known ahead of time (I use the same config for multiple files).

Would it be possible to fallback to the dest in the rollup options if the plugin dest is not provided? For example, `bundle.[hash].js` could be set as the rollup dest. Alternatively, default to converting `bundle.js` to `bundle.[hash].js`.

I'm happy to submit a PR. What do you think?

**Comment by phamann** [comment]
@zdyn Apologies for the delayed response. This sounds like a very sane idea and I'd gladly accept a PR for it, otherwise I can do the work when I next get some spare time.

**Comment by zdyn** [comment]
Apologies for leaving this open for so long. I actually no longer have need for this so I'll go ahead and close it. Thanks for your work!
